### PR TITLE
Update regexp.go

### PR DESCRIPTION
**Pull request by laredoer**
remove fmt.Println(string(debug.Stack()))

### CODE REVIEW

**Comment by snwfdhmp** [comment]
can you explain why did you make the change ?

**Comment by snwfdhmp** [comment]
@wule61 your change doesn't consider whether it's running in production environment or not

**Comment by snwfdhmp** [comment]
if you need that feature please add it as an option

**Comment by wule61** [comment]
> if you need that feature please add it as an option

ok

**Comment by snwfdhmp** [comment]
(otherwise it would break current behavior for users)

**Pull request closed without merging**
